
#!/usr/bin/expect
spawn ../ex01/phonebook
pwd
expect "*\r"
send "ADD\r"
expect "*\r"
send "John\r"
expect "*\r"
send "Doe\r"
expect "*\r"
send "Jojo\r"
expect "*\r"
send "0685744511\r"
expect "*\r"
send "He loves pineapple pizza\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Justin\r"
expect "*\r"
send "Thyme\r"
expect "*\r"
send "Juju\r"
expect "*\r"
send "0645789655\r"
expect "*\r"
send "\r"
expect "*\r"
send "\r"
expect "*\r"
send "\r"
expect "*\r"
send "Sometimes, he drinks sirup without water\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Dee\r"
expect "*\r"
send "Sember\r"
expect "*\r"
send "Dede\r"
expect "*\r"
send "0685210534\r"
expect "*\r"
send "He's not a human\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Polly\r"
expect "*\r"
send "Esther\r"
expect "*\r"
send "Popo\r"
expect "*\r"
send "0678582565\r"
expect "*\r"
send "she thinks the earth is flat\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Alain\r"
expect "*\r"
send "Terieur\r"
expect "*\r"
send "Alal\r"
expect "*\r"
send "0645789655\r"
expect "*\r"
send "He's a dog or a duck\r"
expect "*\r"
send "SEARCH\r"
expect "*\r"
sleep 1
send "Doe\r"
expect "*\r"
send "\r"
expect "*\r"
send "1\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Isabelle A.\r"
expect "*\r"
send "Lafete-Chamboule, Redactrice en Chef de l'Association Internationale des Chats Jongleurs, Amoureuse des Croissants au Chocolat et elève Prematuree de l'ecole de Danse des Pingouins Polaires\r"
expect "*\r"
send "Isa ChocoDanse Pingouin\r"
expect "*\r"
send "06457dedwf\r"
expect "*\r"
send "Isabelle A. Lafete-Chamboule, en depit de sa passion pour les croissants au chocolat, a en realite une aversion profonde pour le chocolat. Elle a passe des annees à cacher cette aversion, faisant semblant d'adorer les douceurs au chocolat pour ne pas froisser les sensibilites culinaires de son entourage. Ses amis pensent qu'elle est la plus grande fan de chocolat, mais en realite, elle le repousse discrètement dans les coins sombres de sa cuisine, esperant que personne ne decouvre jamais son secret sombre et deroutant.\r"
expect "*\r"
send "SEARCH\r"
expect "*\r"
sleep 1
send "85\r"
expect "*\r"
send "6\r"
send "ADD\r"
expect "*\r"
send "Gaston Malappris, Expert en Demontage de Portes Ouvertes et Professeur emerite en Conduite de Trottinette dans les Escaliers\r"
expect "*\r"
send "Ribambelle de Gaffes\r"
expect "*\r"
send "Trottinette\r"
expect "*\r"
send "064575465554\r"
expect "*\r"
send "Gaston Malappris est un expert en demontage de portes ouvertes. Il a passe sa vie à demonter des portes ouvertes, et il est devenu si bon qu'il peut maintenant demonter une porte ouverte en moins de 5 secondes. Il a meme ecrit un livre sur le sujet, intitule \"Comment demonter une porte ouverte en moins de 5 secondes\". Il a egalement ecrit un livre sur la façon de demonter une porte fermee, mais il n'a pas encore ete publie.\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Penelope Noodlewiggle, Chief Bubble Wrap Popper and Grandmaster of Silly Walks\r"
expect "*\r"
send "Penny Bubble Silly\r"
expect "*\r"
send "Bubble\r"
expect "*\r"
send "064575465554\r"
expect "*\r"
send "Despite her reputation as a bubble wrap popper, Penelope Noodlewiggle actually harbors an intense fear of balloons. The mere sight of a balloon sends her into a frenzy of nervous giggles and rapid bubble wrap popping, as she tries to distract herself from the dreaded rubber orbs. Her friends have no clue about this ironic phobia, and she goes to great lengths to avoid birthday parties and circus-themed events.\r"
expect "*\r"
send "SEARCH\r"
expect "*\r"
sleep 1
send "Noodlewiggle\r"
expect "*\r"
send "\r"
expect "*\r"
send "2\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "Pierre\r"
expect "*\r"
send "Dupont\r"
expect "*\r"
send "Pierrot\r"
expect "*\r"
send "0645789655\r"
expect "*\r"
send "Il est un peu bizarre\r"
expect "*\r"
send "SEARCH\r"
expect "*\r"
sleep 1
send "1\r"
expect "*\r"
send "ADD\r"
expect "*\r"
send "\r"
expect "*\r"
send "0\r"
send "EXIT\r"
expect "*\r"